config/routes.rb
Hotelaria::Application.routes.draw do
  get "home/index"

  root :to=> "home#index"

  resources :hospedagens

  resources :contas

  resources :aposentos

  resources :consumos

  resources :hotels

  resources :hospedes

end

app/models/aposento.rb
class Aposento < ActiveRecord::Base
end

app/models/consumo.rb
class Consumo < ActiveRecord::Base
end

app/models/conta.rb
class Conta < ActiveRecord::Base
  belongs_to :consumo
end

app/models/hospedagem.rb
class Hospedagem < ActiveRecord::Base
  belongs_to :conta
  belongs_to :hospede
  belongs_to :aposento
end

app/models/hospede.rb
class Hospede < ActiveRecord::Base
end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
end

app/controllers/aposentos_controller.rb
class AposentosController < InheritedResources::Base
	def build_resource_params
        [params.fetch(:aposento, {}).permit(:hotel_id, :valor, :descricao, :numero )]
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/consumos_controller.rb
class ConsumosController < InheritedResources::Base
    def build_resource_params
        [params.fetch(:consumo, {}).permit(:descricao, :quantidade, :valorUnitario)]
    end
end

app/controllers/contas_controller.rb
class ContasController < InheritedResources::Base
	def build_resource_params
        [params.fetch(:conta, {}).permit(:consumo_id, :valorTotal, :pago )]
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/hospedagens_controller.rb
class HospedagensController < InheritedResources::Base
   def build_resource_params
        [params.fetch(:hospedagem, {}).permit(:conta_id, :hospede_id, :aposento_id, :dataEntrada, :dataSaida )]
    end

end

app/controllers/hospedes_controller.rb
class HospedesController < InheritedResources::Base
    def build_resource_params
        [params.fetch(:hospede, {}).permit(:nome, :cpf, :rg, :telefone)]
    end

end

app/controllers/hotels_controller.rb
class HotelsController < InheritedResources::Base
    def build_resource_params
        [params.fetch(:hotel, {}).permit(:nome, :endereco, :telefone, :cidade, :estado)]
    end
end

app/helpers/aposentos_helper.rb
module AposentosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/consumos_helper.rb
module ConsumosHelper
end

app/helpers/contas_helper.rb
module ContasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hospedagens_helper.rb
module HospedagensHelper
end

app/helpers/hospedes_helper.rb
module HospedesHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/views/aposentos/_form.html.erb
<%= form_for(@aposento) do |f| %>
  <% if @aposento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@aposento.errors.count, "error") %> prohibited this aposento from being saved:</h2>

      <ul>
      <% @aposento.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pkidaposento %><br>
    <%= f.text_field :pkidaposento %>
  </div>
  <div class="field">
    <%= f.label :descricao %><br>
    <%= f.text_field :descricao %>
  </div>
  <div class="field">
    <%= f.label :numero %><br>
    <%= f.text_field :numero %>
  </div>
  <div class="field">
    <%= f.label :valor %><br>
    <%= f.text_field :valor %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/aposentos/_form.html.haml
= semantic_form_for [@aposento] do |form|
  
  = form.input :hotel, :member_label => :nome, :label => 'hotel'
  

  = form.input :valor, :label => 'valor'
  = form.input :descricao, :label => 'descricao'
  = form.input :numero, :label => 'numero'

  = form.submit 'Salvar'

app/views/aposentos/edit.html.erb
<h1>Editing aposento</h1>

<%= render 'form' %>

<%= link_to 'Show', @aposento %> |
<%= link_to 'Back', aposentos_path %>

app/views/aposentos/index.html.erb
<h1>Listing aposentos</h1>

<table>
  <thead>
    <tr>
      <th>Valor</th>
      <th>Descricao</th>
      <th>Numero</th>
      <th>Hotel</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @aposentos.each do |aposento| %>
      <tr>
        <td><%= aposento.valor %></td>
        <td><%= aposento.descricao %></td>
        <td><%= aposento.numero %></td>
        <td><%= aposento.hotel %></td>
        <td><%= link_to 'Show', aposento %></td>
        <td><%= link_to 'Edit', edit_aposento_path(aposento) %></td>
        <td><%= link_to 'Excluir', aposento, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Aposento', new_aposento_path %>

app/views/aposentos/new.html.erb
<h1>New aposento</h1>

<%= render 'form' %>

<%= link_to 'Back', aposentos_path %>

app/views/aposentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pkidaposento:</strong>
  <%= @aposento.pkidaposento %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @aposento.descricao %>
</p>

<p>
  <strong>Numero:</strong>
  <%= @aposento.numero %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @aposento.valor %>
</p>

<%= link_to 'Edit', edit_aposento_path(@aposento) %> |
<%= link_to 'Back', aposentos_path %>

app/views/consumos/_form.html.haml
= semantic_form_for [@consumo] do |form|
  = form.input :descricao, :label => 'descricao'
  = form.input :quantidade, :label => 'quantidade'
  = form.input :valorUnitario, :label => 'valorUnitario'	
  = form.submit 'Salvar'

app/views/consumos/edit.html.erb
<h1>Editing consumo</h1>

<%= render 'form' %>

<%= link_to 'Show', @consumo %> |
<%= link_to 'Back', consumos_path %>

app/views/consumos/index.html.erb
<h1>Listing consumos</h1>

<table>
  <thead>
    <tr>
      <th>Descricao</th>
      <th>Quantidade</th>
      <th>Valorunitario</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @consumos.each do |consumo| %>
      <tr>
        <td><%= consumo.descricao %></td>
        <td><%= consumo.quantidade %></td>
        <td><%= consumo.valorUnitario %></td>
        <td><%= link_to 'Show', consumo %></td>
        <td><%= link_to 'Edit', edit_consumo_path(consumo) %></td>
        <td><%= link_to 'Excluir', consumo, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Consumo', new_consumo_path %>

app/views/consumos/new.html.erb
<h1>New consumo</h1>

<%= render 'form' %>

<%= link_to 'Back', consumos_path %>

app/views/consumos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>descricao:</strong>
  <%= @consumo.descricao %>
</p>

<p>
  <strong>quantidade:</strong>
  <%= @consumo.quantidade %>
</p>

<p>
  <strong>valorUnitario:</strong>
  <%= @consumo.valorUnitario %>
</p>

<%= link_to 'Edit', edit_consumo_path(@consumo) %> |
<%= link_to 'Back', consumos_path %>

app/views/contas/_form.html.haml
= semantic_form_for [@conta] do |form|
  
  = form.input :consumo, :member_label => :descricao, :label => 'consumo'
  

  = form.input :valorTotal, :label => 'valorTotal'
  = form.input :pago, :label => 'pago'
 

  = form.submit 'Salvar'

app/views/contas/edit.html.erb
<h1>Editing conta</h1>

<%= render 'form' %>

<%= link_to 'Show', @conta %> |
<%= link_to 'Back', contas_path %>

app/views/contas/index.html.erb
<h1>Listing contas</h1>

<table>
  <thead>
    <tr>
      <th>Valortotal</th>
      <th>Pago</th>
      <th>Consumo</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @contas.each do |conta| %>
      <tr>
        <td><%= conta.valorTotal %></td>
        <td><%= conta.pago %></td>
        <td><%= conta.consumo %></td>
        <td><%= link_to 'Show', conta %></td>
        <td><%= link_to 'Edit', edit_conta_path(conta) %></td>
        <td><%= link_to 'Excluir', conta, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Conta', new_conta_path %>

app/views/contas/new.html.erb
<h1>New conta</h1>

<%= render 'form' %>

<%= link_to 'Back', contas_path %>

app/views/contas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>valorTotal:</strong>
  <%= @conta.valorTotal %>
</p>

<p>
  <strong>pago:</strong>
  <%= @conta.pago %>
</p>

<p>
  <strong>consumo:</strong>
  <%= @conta.consumo.descricao %>
</p>

<%= link_to 'Edit', edit_conta_path(@conta) %> |
<%= link_to 'Back', contas_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/hospedagens/_form.html.haml
= semantic_form_for [@hospedagem] do |form|
  
  = form.input :conta, :member_label => :pago, :label => 'conta'
  = form.input :hospede, :member_label => :nome, :label => 'hospede'
  = form.input :aposento, :member_label => :descricao, :label => 'aposento'


  = form.input :dataEntrada, :label => 'dataEntrada'
  = form.input :dataSaida, :label => 'dataSaida'
  

  = form.submit 'Salvar'

app/views/hospedagens/edit.html.erb
<h1>Editing hospedagem</h1>

<%= render 'form' %>

<%= link_to 'Show', @hospedagem %> |
<%= link_to 'Back', hospedagens_path %>

app/views/hospedagens/index.html.erb
<h1>Listing hospedagens</h1>

<table>
  <thead>
    <tr>
      <th>Dataentrada</th>
      <th>Datasaida</th>
      <th>Conta</th>
      <th>Hospede</th>
      <th>Aposento</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @hospedagens.each do |hospedagem| %>
      <tr>
        <td><%= hospedagem.dataEntrada %></td>
        <td><%= hospedagem.dataSaida %></td>
        <td><%= hospedagem.conta %></td>
        <td><%= hospedagem.hospede %></td>
        <td><%= hospedagem.aposento %></td>
        <td><%= link_to 'Show', hospedagem %></td>
        <td><%= link_to 'Edit', edit_hospedagem_path(hospedagem) %></td>
        <td><%= link_to 'Excluir', hospedagem, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hospedagem', new_hospedagem_path %>

app/views/hospedagens/new.html.erb
<h1>New hospedagem</h1>

<%= render 'form' %>

<%= link_to 'Back', hospedagens_path %>

app/views/hospedagens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>dataEntrada:</strong>
  <%= @hospedagem.dataEntrada %>
</p>

<p>
  <strong>dataSaida:</strong>
  <%= @hospedagem.dataSaida %>
</p>

<p>
  <strong>conta:</strong>
  <%= @hospedagem.conta.pago %>
</p>

<p>
  <strong>hospede:</strong>
  <%= @hospedagem.hospede.nome %>
</p>

<p>
  <strong>aposento:</strong>
  <%= @hospedagem.aposento.descricao %>
</p>

<%= link_to 'Edit', edit_hospedagem_path(@hospedagem) %> |
<%= link_to 'Back', hospedagens_path %>

app/views/hospedes/_form.html.haml
= semantic_form_for [@hospede] do |form|
  = form.input :nome, :label => 'nome'
  = form.input :cpf, :label => 'cpf'
  = form.input :rg, :label => 'rg'
  = form.input :telefone, :label => 'telefone'	
  = form.submit 'Salvar'

app/views/hospedes/edit.html.erb
<h1>Editing hospede</h1>

<%= render 'form' %>

<%= link_to 'Show', @hospede %> |
<%= link_to 'Back', hospedes_path %>

app/views/hospedes/index.html.erb
<h1>Listing hospedes</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Cpf</th>
      <th>Rg</th>
      <th>Telefone</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @hospedes.each do |hospede| %>
      <tr>
        <td><%= hospede.nome %></td>
        <td><%= hospede.cpf %></td>
        <td><%= hospede.rg %></td>
        <td><%= hospede.telefone %></td>
        <td><%= link_to 'Show', hospede %></td>
        <td><%= link_to 'Edit', edit_hospede_path(hospede) %></td>
        <td><%= link_to 'Excluir', hospede, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hospede', new_hospede_path %>

app/views/hospedes/new.html.erb
<h1>New hospede</h1>

<%= render 'form' %>

<%= link_to 'Back', hospedes_path %>

app/views/hospedes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>nome:</strong>
  <%= @hospede.nome %>
</p>

<p>
  <strong>cpf:</strong>
  <%= @hospede.cpf %>
</p>

<p>
  <strong>rg:</strong>
  <%= @hospede.rg %>
</p>

<p>
  <strong>telefone:</strong>
  <%= @hospede.telefone %>
</p>

<%= link_to 'Edit', edit_hospede_path(@hospede) %> |
<%= link_to 'Back', hospedes_path %>

app/views/hotels/_form.html.haml
= semantic_form_for [@hotel] do |form|
  = form.input :nome, :label => 'nome'
  = form.input :endereco, :label => 'endereco'
  = form.input :telefone, :label => 'telefone'	
  = form.input :cidade, :label => 'cidade'
  = form.input :estado, :label => 'estado'
  = form.submit 'Salvar'

app/views/hotels/edit.html.erb
<h1>Editing hotel</h1>

<%= render 'form' %>

<%= link_to 'Show', @hotel %> |
<%= link_to 'Back', hotels_path %>

app/views/hotels/index.html.erb
<h1>Listing hotels</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Endereco</th>
      <th>Telefone</th>
      <th>Cidade</th>
      <th>Estado</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @hotels.each do |hotel| %>
      <tr>
        <td><%= hotel.nome %></td>
        <td><%= hotel.endereco %></td>
        <td><%= hotel.telefone %></td>
        <td><%= hotel.cidade %></td>
        <td><%= hotel.estado %></td>
        <td><%= link_to 'Show', hotel %></td>
        <td><%= link_to 'Edit', edit_hotel_path(hotel) %></td>
        <td><%= link_to 'Excluir', hotel, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hotel', new_hotel_path %>

app/views/hotels/new.html.erb
<h1>New hotel</h1>

<%= render 'form' %>

<%= link_to 'Back', hotels_path %>

app/views/hotels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>nome:</strong>
  <%= @hotel.nome %>
</p>

<p>
  <strong>endereco:</strong>
  <%= @hotel.endereco %>
</p>

<p>
  <strong>telefone:</strong>
  <%= @hotel.telefone %>
</p>

<p>
  <strong>cidade:</strong>
  <%= @hotel.cidade %>
</p>

<p>
  <strong>estado:</strong>
  <%= @hotel.estado %>
</p>

<%= link_to 'Edit', edit_hotel_path(@hotel) %> |
<%= link_to 'Back', hotels_path %>